-- AlterTable
ALTER TABLE "GlobalSettings" ADD COLUMN     "mapZoom" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN     "mapZoomMax" INTEGER NOT NULL DEFAULT 18,
ADD COLUMN     "mapZoomMin" INTEGER NOT NULL DEFAULT 10;
